
### GET Holiday
GET http://localhost:3333/feriados/1400282/2020-12-25

### Store mobile holiday
PUT  http://localhost:3333/feriados/1400282/carnaval


### GET CARNAVAL
GET http://localhost:3333/feriados/1400282/2020-02-25

### DELETE CARNAVAL
DELETE http://localhost:3333/feriados/1400282/carnaval

### Store mobile holiday
PUT  http://localhost:3333/feriados/1400282/pascoa

### GET PASCOA
GET http://localhost:3333/feriados/1400282/2020-04-12

### Store my birthday holiday
PUT  http://localhost:3333/feriados/1400282/04-27 HTTP/1.1
content-type: application/json

{
   "name": "Márlon Birthday"
}


###GET my birthday holiday
GET http://localhost:3333/feriados/1400282/2020-04-27

###DELETE my birthdat holiday
DELETE http://localhost:3333/feriados/1400282/04-27

###GET DIA TRABALHADOR
GET http://localhost:3333/feriados/4305439/2020-05-01

###POST CONSCIENCIA NEGRA
PUT  http://localhost:3333/feriados/33/11-20/
content-type: application/json

{
   "name": "Consciência Negra"
}

###DELETE CONSCIENCIA NEGRA
DELETE http://localhost:3333/feriados/33/11-20/

###DELETE CONSCIENCIA NEGRA
DELETE http://localhost:3333/feriados/3304557/11-20/

###DELETE FERIADO NACIONAL
DELETE http://localhost:3333/feriados/3304557/05-01/